### ISSUE TITLE
Learning Rate schedule  for 3x Fixmatch

### ISSUE THREAD

**Issue by mingkai-zheng** [amazon-research/exponential-moving-average-normalization#2]
Thank you for your amazing work !
Would you like to provide the Learning Rate schedule for 3x Fixmatch?  Do you just simply drop the lr by 10x at 180 and 240 epoch?

**Comment by zhaoweicai** [comment]
Hi, since it was quite annoying to tune the LR drop schedule, we simply used cosine learning rate schedule for 3x experiments.

**Comment by mingkai-zheng** [comment]
Would you like to provide the training details (or script) for 3x Fixmatch (EMAN version)? I could successfully reproduce the result for 1x Fixmatch (100epochs with cosine scheduler: 69.8 vs Step scheduler in Paper 69.2),  but for 3x Fixmatch I can only get 70.8 vs Paper accuracy 72.8
