### ISSUE TITLE
Would you like to provde the training script for 3x Fixmatch, Thank you !

### ISSUE THREAD

**Issue by mingkai-zheng** [amazon-research/exponential-moving-average-normalization#3]
Would you like to provide the training script for 3x Fixmatch? thank you !
![WeChatWorkScreenshot_d5c227fe-84c3-4df7-9b17-5d0fdf6416f5](https://user-images.githubusercontent.com/30642498/136693670-46178e57-1318-4f04-8c0f-db75527773cc.png)

**Comment by zhaoweicai** [comment]
please try
```
python main_fixmatch.py \
  --arch FixMatch --backbone resnet50_encoder \
  --eman \
  --lr 0.03 \
  --epochs 300 --cos \
  --warmup-epoch 5 \
  --trainindex_x train_10p_index.csv --trainindex_u train_90p_index.csv \
  --dist-url 'tcp://localhost:10001' --multiprocessing-distributed --world-size 1 --rank 0 \
  /path/to/imagenet
```
Let me know if you can reproduce the results.

**Comment by mingkai-zheng** [comment]
Thank you so much for your help!  I have successfully reproduced the result!  I will close the issue now
